linux:
  debian:
    supports_systemd: true
    supports_cron: true
    supports_env: true
    cron_tab_path: /var/spool/cron/crontabs/{user}
    cron_log_path: /var/log/syslog
    systemd_unit_path: /etc/systemd/system
    env_files:
      - /etc/environment
      - ~/.profile
    package_manager: apt

  redhat:
    supports_systemd: true
    supports_cron: true
    supports_env: true
    cron_tab_path: /var/spool/cron/{user}
    cron_log_path: /var/log/cron
    systemd_unit_path: /usr/lib/systemd/system
    env_files:
      - /etc/environment
      - ~/.bash_profile
    package_manager: dnf

  suse:
    supports_systemd: false
    supports_cron: true
    supports_env: false
    cron_tab_path: /var/spool/cron/tabs/{user}
    cron_log_path: /var/log/messages
    systemd_unit_path: /usr/lib/systemd/system
    env_files:
      - /etc/environment
      - ~/.bashrc
    package_manager: zypper

  arch:
    supports_systemd: true
    supports_cron: true
    supports_env: true
    cron_tab_path: /var/spool/cron/{user}
    cron_log_path: /var/log/cron.log
    systemd_unit_path: /etc/systemd/system
    env_files:
      - /etc/environment
      - ~/.bash_profile
    package_manager: pacman
windows:
  win10:
    supports_systemd: false
    supports_cron: false
macos:
  ventura:
    supports_systemd: false
    supports_cron: true